name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: output/github-contribution-grid-snake.svg

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando Snake Animation"
          add: "output/github-contribution-grid-snake.svg"
